name: 'Release (Github)'
description: 'Github release'
inputs:
  version:
    description: 'Release version number'
    required: true
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
  - name: Create GH release
    env:
      GH_TOKEN: ${{ github.TOKEN }}
    shell: bash
    run: |
      gh release create ${{ github.ref_name }}
