name: 'Setup (Ruby)'
description: 'Setup Ruby'
inputs:
  ruby-version:
    description: 'Ruby version'
    required: true
runs:
  using: "composite"
  steps:
  - uses: ruby/setup-ruby@v1
    with:
      ruby-version: ${{ inputs.ruby-version }}
      bundler-cache: true
