name: 'Run scan (brakeman)'
description: 'Run security scan (brakeman)'
inputs:
  ruby-version:
    description: 'Ruby version'
    required: true
runs:
  using: "composite"
  steps:
  - name: Checkout code
    uses: actions/checkout@v6

  - name: Setup Ruby
    uses: nu12/templates/actions/setup/ruby/v1@main
    with:
      ruby-version: ${{ inputs.ruby-version }}

  - name: Scan for common Rails security vulnerabilities using static analysis
    run: bin/brakeman --no-pager
    shell: bash

  - name: Scan for security vulnerabilities in JavaScript dependencies
    run: bin/importmap audit
    shell: bash
